bookmarks/urls.py
from django.conf.urls import url, patterns, include
from bookmarks import views
from django.contrib.auth.views import login, logout

urlpatterns = patterns('',
    url(r'^$', views.index, name = 'index'),
    url(r'^suggestion/$', views.suggestion, name = 'suggestion'),
    url(r'^subscribe-(?P<id>[0-9]+)/$', views.subscribe, name = 'subscribe'),
    url(r'^unsubscribe-(?P<id>[0-9]+)/$', views.unsubscribe, name = 'unsubscribe'),
    url(r'^my/$', views.my, name = 'my'),
    url(r'^add/$', views.add, name = 'add'),
    url(r'^login/$', login, name = 'login'),
    url(r'^logout/$', logout , name = 'logout'),
    url(r'^registration/$', views.registration, name = 'registration'),
)

fonts/urls.py
from django.conf.urls import url, patterns, include
from fonts import views

urlpatterns = patterns('',
    url(r'^(?P<name>.+)$', views.index, name='index'),
)          

zakladnik/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^', include('bookmarks.urls', namespace = 'bookmarks')),
    url(r'^fonts/', include('fonts.urls', namespace = 'fonts')),
    url(r'^admin/', include(admin.site.urls)),
)

bookmarks/models.py
from django.db import models
from django.contrib import auth

class Profile(models.Model):
    user = models.OneToOneField(auth.models.User)

class Bookmark(models.Model):
    title = models.CharField(max_length = 255)
    url = models.CharField(max_length = 255)
    description = models.TextField()
    author = models.ForeignKey(Profile)
    subscribers = models.ManyToManyField(Profile, related_name = 'subscribers')

fonts/models.py
from django.db import models

# Create your models here.

bookmarks/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from bookmarks.models import Bookmark

class BookmarkForm(forms.ModelForm):
    url = forms.URLField(required = True)
    title = forms.Field(required = False)
    class Meta:
        model = Bookmark
        fields = ['url', 'title', 'description']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def clean(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if password and password != confirm_password:
            raise forms.ValidationError("Hasło musi być potwierdzone")

        return self.cleaned_data

bookmarks/views.py
# -*- coding: utf-8 -*-
from django.contrib import auth, messages
from django.core.urlresolvers import reverse
from django.db.models import Count
from django.shortcuts import render, redirect
from bookmarks.forms import UserForm, BookmarkForm
from bookmarks.models import Profile, Bookmark


def index(request):
    bookmarks = Bookmark.objects.all()
    subscribedBookmarks = None
    try:
        profile = Profile.objects.get(user_id = request.user.id)
        subscribedBookmarks = Bookmark.objects.filter(subscribers = profile)
    except:
        profile = None

    return render(request, 'bookmarks/index.html', {
        'bookmarks': bookmarks,
        'subscribedBookmarks': subscribedBookmarks,
    })

def suggestion(request):
    profile = Profile.objects.get(user_id = request.user.id)

    subscribed = Bookmark.objects.filter(subscribers = profile)
    flatList = subscribed.values_list('id', flat = True)
    bookmarks = Bookmark.objects.annotate(num_sub = Count('subscribers')).exclude(subscribers = profile)\
        .exclude(id__in = flatList).filter(num_sub__gt = 1).order_by('-num_sub')

    return render(request, 'bookmarks/suggestion.html', {
        'bookmarks': bookmarks
    })

def subscribe(request, id):
    profile = Profile.objects.get(user_id = request.user.id)
    bookmark = Bookmark.objects.get(pk=id)
    bookmark.subscribers.add(profile)

    return redirect(reverse('bookmarks:index'))

def unsubscribe(request, id):
    profile = Profile.objects.get(user_id = request.user.id)
    bookmark = Bookmark.objects.get(pk=id)
    bookmark.subscribers.remove(profile)

    return redirect(reverse('bookmarks:my'))

def my(request):
    profile = Profile.objects.get(user_id = request.user.id)
    bookmarks = Bookmark.objects.filter(subscribers = profile)

    return render(request, 'bookmarks/my.html', {
        'bookmarks': bookmarks
    })

def add(request):
    if request.method == 'POST':
        form = BookmarkForm(request.POST)
        if form.is_valid():
            bookmark = Bookmark.objects.get(url=form.cleaned_data['url'])
            profile = Profile.objects.get(user_id = request.user.id)
            if bookmark is None:
                bookmark = form.save(commit = False)
                bookmark.author = profile
                bookmark.save()
            bookmark.subscribers.add(profile)

            return redirect(reverse('bookmarks:index'))
    else:
        form = BookmarkForm()

    return render(request, 'bookmarks/add.html', {
        'form' : form
    })

def registration(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.set_password(user.password)
            user.save()
            profile = Profile()
            profile.user = user
            profile.save()

            return redirect(reverse('bookmarks:index'))
    else:
        form = UserForm()

    return render(request, 'registration/registration.html', {
        'form' : form
    })

def login(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')

    user = auth.authenticate(username = username, password = password)
    if user is not None and user.is_active:
        auth.login(request, user)
        messages.add_message(request, messages.SUCCESS, 'Właśnie się zalogowałeś')

        return redirect(reverse('bookmarks:index'))

    return render(request, 'bookmarks/login.html')

fonts/views.py
from django.http import HttpResponse
from zakladnik import settings
from os.path import join

def index(request, name):
    response = HttpResponse(content_type = "application/octet-stream")
    path = join(settings.BASE_DIR ,'fonts' , settings.STATIC_URL[1:], 'fonts', name)
    with open(path, 'r') as f: response.content = f.read()

    return response

bookmarks/templates/bookmarks/add.html
{% extends 'layout.html' %}


{% block content %}
<form action="" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Dodaj">
</form>
{% endblock %}

bookmarks/templates/bookmarks/index.html
{% extends 'layout.html' %}


    {% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    <article data-ride="carousel" class="carousel slide" id="carousel-example-captions">
      <ol class="carousel-indicators">
        <li class="" data-slide-to="0" data-target="#carousel-example-captions"></li>
        <li data-slide-to="1" data-target="#carousel-example-captions" class=""></li>
        <li data-slide-to="2" data-target="#carousel-example-captions" class="active"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item">
          <img alt="900x500" data-src="holder.js/900x500/auto/#777:#777" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI5MDAiIGhlaWdodD0iNTAwIj48cmVjdCB3aWR0aD0iOTAwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iIzc3NyIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjQ1MCIgeT0iMjUwIiBzdHlsZT0iZmlsbDojNzc3O2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjU2cHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+OTAweDUwMDwvdGV4dD48L3N2Zz4=">
          <div class="carousel-caption">
            <h3>First slide label</h3>
            <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
          </div>
        </div>
        <div class="item">
          <img alt="900x500" data-src="holder.js/900x500/auto/#666:#666" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI5MDAiIGhlaWdodD0iNTAwIj48cmVjdCB3aWR0aD0iOTAwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iIzY2NiIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjQ1MCIgeT0iMjUwIiBzdHlsZT0iZmlsbDojNjY2O2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjU2cHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+OTAweDUwMDwvdGV4dD48L3N2Zz4=">
          <div class="carousel-caption">
            <h3>Second slide label</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
          </div>
        </div>
        <div class="item active">
          <img alt="900x500" data-src="holder.js/900x500/auto/#555:#5555" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI5MDAiIGhlaWdodD0iNTAwIj48cmVjdCB3aWR0aD0iOTAwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iIzU1NSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjQ1MCIgeT0iMjUwIiBzdHlsZT0iZmlsbDojNTU1NTtmb250LXdlaWdodDpib2xkO2ZvbnQtc2l6ZTo1NnB4O2ZvbnQtZmFtaWx5OkFyaWFsLEhlbHZldGljYSxzYW5zLXNlcmlmO2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPjkwMHg1MDA8L3RleHQ+PC9zdmc+">
          <div class="carousel-caption">
            <h3>Third slide label</h3>
            <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
          </div>
        </div>
      </div>
      <a data-slide="prev" href="#carousel-example-captions" class="left carousel-control">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a data-slide="next" href="#carousel-example-captions" class="right carousel-control">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </article>
    <div class="row container bookmarks">
        {% for bookmark in bookmarks %}

            <div class="col-md-4">
                <div>
                    <h3>{{ bookmark.title }}</h3>
                    <p>
                        <a href="{{ bookmark.url }}">
                            {% if bookmark.title %}
                                {{ bookmark.title }}
                            {% else %}
                                {{ bookmark.url }}
                            {% endif %}
                        </a>
                    </p>
                    <p>
                    {% if bookmark not in subscribedBookmarks.all %}
                        <a href="{% url 'bookmarks:subscribe' id=bookmark.id %}">Subskrybuj</a>
                    {% else %}
                        <a href="{% url 'bookmarks:unsubscribe' id=bookmark.id %}">Odsubskrybuj</a>
                    {% endif %}
                    </p>
                </div>
            </div>
        {% endfor %}
    </div>
    {% endblock %}

bookmarks/templates/bookmarks/my.html
{% extends 'layout.html' %}

{% block content %}
    {% for bookmark in bookmarks %}
        <div class="col-md-4">
            <div>
                <h3>{{ bookmark.title }}</h3>
                <p>
                    <a href="{{ bookmark.url }}">
                        {% if bookmark.title %}
                            {{ bookmark.title }}
                        {% else %}
                            {{ bookmark.url }}
                        {% endif %}
                    </a>
                </p>
                <p>
                    <a href="{% url 'bookmarks:unsubscribe' id=bookmark.id %}">Odsubskrybuj</a>
                </p>
            </div>
        </div>
    {% endfor %}
{% endblock %}

bookmarks/templates/bookmarks/suggestion.html
{% extends 'layout.html' %}

{% block content %}
    <div class="row container bookmarks">
        {% for bookmark in bookmarks %}
            <div class="col-md-4">
                <div>
                    <h3>{{ bookmark.title }}</h3>
                    <p>
                        <a href="{{ bookmark.url }}">
                            {% if bookmark.title %}
                                {{ bookmark.title }}
                            {% else %}
                                {{ bookmark.url }}
                            {% endif %}
                        </a>
                    </p>
                    <p>
                        <a href="{% url 'bookmarks:subscribe' id=bookmark.id %}">Subskrybuj</a>
                    </p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

bookmarks/templates/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" type="text/css" href="{% static 'bookmarks/76ae8c0.css' %}" />
        {% endblock %}
        <link rel="icon" type="image/x-icon" href="{{ icon }}" />
    </head>
    <body>
        {% block header %}
            <header class="header">
                <nav class="container-fluid nav navbar-inverse">
                    <h3 class="brand"><a href="{% url 'bookmarks:index' %}">Zakładnik</a></h3>
                    <ul class="nav nav-tabs">
                        {% url 'bookmarks:suggestion' as currentUrl %}
                        <li {% if request.get_full_path == currentUrl %}class="active"{% endif %}>
                            <a href="{% url 'bookmarks:suggestion' %}">
                                <span class="glyphicon glyphicon-share"></span>Sugestie
                            </a>
                        </li>
                        {% url 'bookmarks:my' as currentUrl %}
                        <li {% if request.get_full_path == currentUrl %}class="active"{% endif %}>
                            <a href="{% url 'bookmarks:my' %}">
                                <span class="glyphicon glyphicon-check"></span>Moje
                            </a>
                        </li>
                        {% url 'bookmarks:add' as currentUrl %}
                        <li {% if request.get_full_path == currentUrl %}class="active"{% endif %}>
                            <a href="{% url 'bookmarks:add' %}">
                                <span class="glyphicon glyphicon-plus"></span>Dodaj
                            </a>
                        </li>
                {% if request.user.is_authenticated == False %}
                        {% url 'bookmarks:registration' as currentUrl %}
                        <li class="pull-right {% if request.get_full_path == currentUrl %}active{% endif %}">
                            <a href="{% url 'bookmarks:registration' %}">
                                <span class="glyphicon glyphicon-pencil"></span>Rejestracja
                            </a>
                        </li>
                        {% url 'bookmarks:login' as currentUrl %}
                        <li class="pull-right {% if request.get_full_path == currentUrl %}active{% endif %}">
                            <a href="{% url 'bookmarks:login' %}">
                                <span class="glyphicon glyphicon-user"></span>Logowanie
                            </a>
                        </li>
                {% else %}
                        <li class="pull-right">
                            <a href="{% url 'bookmarks:logout' %}?next={% url 'bookmarks:index' %}">
                                <span class="glyphicon glyphicon-user"></span>Wyloguj {{ request.user.username }}
                            </a>
                        </li>
                {% endif %}
                    </ul>
                </nav>
            </header>
        {% endblock %}


<section class="container">
        {% block body %}
            {% block content %}{% endblock %}
        {% endblock %}
</section>
{% block footer %}
<footer>
    <div class="navbar-inverse">
        <p class="container text-info">aaaa</p>
    </div>
</footer>

{% endblock %}
        {% block javascripts %}
        <script type="text/javascript" src="{% static 'bookmarks/js/jquery-2.1.0.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'bookmarks/js/bootstrap.min.js' %}"></script>
        {% endblock %}
    </body>
</html>